FROM archlinux:latest

ENV TZ=Europe/Warsaw

RUN pacman -Syu --noconfirm \
        sudo \
        bash \
        ca-certificates \
        curl \
        git \
        tzdata \
    && useradd -m -s /bin/bash test \
    && echo 'test ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/test \
    && chmod 0440 /etc/sudoers.d/test \
    && pacman -Scc --noconfirm

USER test
WORKDIR /test

CMD ["bash"]
